name: Docker Image CI

on:
  push:
    branches:
      - benchmark
      - master
  pull_request:
    branches: [ benchmark ]

jobs:
        
  cwag-precommit:
          
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    steps:
    - uses: actions/checkout@v2
    - name: Export Magma root path
      run: echo "MAGMA_ROOT=${PWD}" >> $GITHUB_ENV
    - name: Run golang_before_install.sh script
      run: ./circleci/golang_before_install.sh
    - name: Run go
      run: |
          cd ${MAGMA_ROOT}/cwf/gateway
          go mod download
    - name: Run make
      run: |
          cd ${MAGMA_ROOT}/cwf/gateway
          make -C ${MAGMA_ROOT}/cwf/gateway precommit
          cd ${MAGMA_ROOT}/cwf/gateway
          make -C ${MAGMA_ROOT}/cwf/gateway/integ_tests precommit
#    - magma_slack_notify
