name: xwfm-test

on:
  push:
    branches:
      - benchmark
      - master
  pull_request:
    branches: [ benchmark ]

jobs:

  xwfm-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment Variables
      run: |
            echo "MAGMA_ROOT=${PWD}" >> $GITHUB_ENV
            echo "RUN_UID=${RANDOM}" >> $GITHUB_ENV
    - name: Build the docker-compose stack
      run: |
           cd ${MAGMA_ROOT}/xwf/docker/
           docker-compose up -d
    - name: Loading openvswitch kernel module
      run: sudo modprobe openvswitch
    - name: Run docker compose
      run: |
            env
            docker login -u ${XWF_ARTIFACTORY_USER} -p ${XWF_ARTIFACTORY_API_KEY} ${XWF_ARTIFACTORY_LINK}
            docker-compose pull || true
            docker-compose build --parallel && docker-compose up -d && docker exec tests pytest --log-cli-level=info code/tests.py
            #      - when:
            #condition: <<parameters.notify_magma_ci>>
            #steps: magma_slack_notify
            #- when:
            #condition: <<parameters.notify_xwfm_ci>>
            #steps:
            #- magma_slack_notify:
            #    channel: "#xwfm_ci"
